# hAppS
canteen:
  canteen_url : "https://www.stwh-portal.de/mensa/webapp"
  canteen_id : <your_canteen_id>
  price_id : 1 for students, 2 for employees, 3 for guests
  pay_id : 1 for card, 2 for cash
departure:
  departure_url : "https://abfahrten.uestra.de/proxy2/efa/XML_DM_REQUEST"
  station_id : <id_of_station> # found on https://abfahrten.uestra.de
matrix_server:
  base_url: <base_url_of_matrix_instance>
  user_id: <user_id_of_bot_user>
  access_token: <access_token> # get via tokengen command
  room_id: <id_of_room_to_post_to>
